### Numpy
This section is for learning numpy

In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

In [2]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
x.dtype

dtype('int64')

In [4]:
x.shape

(5,)

In [5]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(Y)
print(Y.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [6]:
x = np.zeros((3, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
x = np.full((2, 3), 7)
print(x)

[[7 7 7]
 [7 7 7]]


In [8]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
x = np.diag([1, 2, 3, 4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [10]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
x = np.arange(4, 20, 3)
print(x)

[ 4  7 10 13 16 19]


In [12]:
x = np.linspace(0, 25, 10, endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [13]:
x = np.arange(20)
print(x.reshape(4, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
x = np.reshape(x, (10, 2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [15]:
x = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [16]:
x = np.random.random((2, 3))
print(x)

[[0.18960796 0.8185299  0.73897577]
 [0.40388897 0.24954281 0.96155057]]


In [17]:
x = np.random.randint(0, 10, (3, 4))
print(x)

[[1 7 2 7]
 [3 2 0 9]
 [7 0 3 7]]


In [18]:
x = np.random.normal(0, 0.1, (1000, 1000))
print(x)

[[ 0.12791779  0.04191956  0.18017749 ... -0.03193681  0.04573659
  -0.03792457]
 [ 0.11633753  0.0572237   0.06161344 ...  0.07158694 -0.05129034
   0.09131783]
 [ 0.08409684  0.03305277  0.00069848 ... -0.07777756  0.02934468
  -0.05637042]
 ...
 [-0.05915098 -0.02095242 -0.06692974 ... -0.02571212 -0.0755544
   0.10607452]
 [-0.05910322 -0.04803632  0.00905751 ... -0.00216188  0.13150599
  -0.06385742]
 [ 0.10399265 -0.22386529 -0.00831083 ... -0.04349479  0.07235874
  -0.15182217]]


In [19]:
x = np.arange(20)

print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [20]:
x = np.reshape(x, (4, 5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [21]:
x = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


### Accessing, Deleting and Inserting Elements into ndarrays

In [22]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [23]:
print('1st element:', x[0])
print('3rd element:', x[2])
print('Last element:', x[-1])

1st element: 1
3rd element: 3
Last element: 5


In [24]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [25]:
x = np.arange(1, 10).reshape(3, 3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
print('Element at 1st row, 2nd column:', x[0, 1])
print('Element at 3rd row, 1st column:', x[2, 0])

Element at 1st row, 2nd column: 2
Element at 3rd row, 1st column: 7


In [27]:
x[0,0] = 20
print(x)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [28]:
w = np.delete(x, 1, axis=1)  # Delete 2nd column
print(w)

[[20  3]
 [ 4  6]
 [ 7  9]]


In [29]:
y = np.append(w, [[10], [11], [12]], axis=1)  # Append new column
print(y)

[[20  3 10]
 [ 4  6 11]
 [ 7  9 12]]


In [30]:
x = np.array([1, 2, 5, 6, 7])

Y = np.array([[1, 2, 3], [7, 8, 9]])

print(x)
print()
print(Y)

[1 2 5 6 7]

[[1 2 3]
 [7 8 9]]


In [31]:
x = np.insert(x, 3, 3)  # Insert '3' at index 3
print(x)

[1 2 5 3 6 7]


In [32]:
w = np.insert(Y, 2, [4, 5, 6], axis=0)  # Insert new row at index 1
print(w)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [33]:
x = np.array([1, 2])

Y = np.array([[3, 4], [5, 6]])

print(x)
print()
print(Y)

[1 2]

[[3 4]
 [5 6]]


In [34]:
z = np.vstack((x, Y)) # Stack arrays vertically
print(z)

[[1 2]
 [3 4]
 [5 6]]


Slicing ndarrays
1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

nb: the end index in 1 and 3 are excluded

In [35]:
x = np.arange(1, 21).reshape(4, 5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [36]:
z = x[1:4, 2:5] # Slicing rows 1 to 3 and columns 2 to 4
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [37]:
z = x[:, 2]
print(z)

[ 3  8 13 18]


In [38]:
z = x[:, 2:3]
print(z)

[[ 3]
 [ 8]
 [13]
 [18]]


In [39]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [40]:
z = x[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [41]:
z[2, 2] = 100
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 100]]


In [42]:
print(x)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 100]]


In [43]:
x = np.arange(1, 21).reshape(4, 5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [44]:
z = x[1:, 2:].copy()
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [45]:
z[2, 2] = 100
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 100]]


In [46]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [47]:
indices = np.array([1, 3])
print(indices)

[1 3]


In [48]:
y = x[indices, :]
print(y)

[[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [49]:
z = x[:, indices]
print(z)

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


In [50]:
z = np.diag(x)
print(z)

[ 1  7 13 19]
