### Numpy
This section is for learning numpy

In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

In [2]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
x.dtype

dtype('int64')

In [4]:
x.shape

(5,)

In [5]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(Y)
print(Y.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [6]:
x = np.zeros((3, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
x = np.full((2, 3), 7)
print(x)

[[7 7 7]
 [7 7 7]]


In [8]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
x = np.diag([1, 2, 3, 4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [10]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
x = np.arange(4, 20, 3)
print(x)

[ 4  7 10 13 16 19]


In [12]:
x = np.linspace(0, 25, 10, endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [13]:
x = np.arange(20)
print(x.reshape(4, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
x = np.reshape(x, (10, 2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [15]:
x = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [16]:
x = np.random.random((2, 3))
print(x)

[[0.27035437 0.65295717 0.41076586]
 [0.52244811 0.99719509 0.60981371]]


In [17]:
x = np.random.randint(0, 10, (3, 4))
print(x)

[[7 0 9 1]
 [1 7 3 6]
 [1 6 1 3]]


In [18]:
x = np.random.normal(0, 0.1, (1000, 1000))
print(x)

[[-0.04985628 -0.07177319 -0.00327835 ... -0.03230963  0.01979404
   0.01362959]
 [-0.03855162  0.05021981  0.01799029 ...  0.02248464 -0.09402062
  -0.10065203]
 [-0.00415199  0.11496807 -0.05495953 ...  0.09687336 -0.02459031
   0.11865666]
 ...
 [-0.05802012  0.04374899 -0.06454477 ... -0.19606486 -0.0929618
  -0.09272683]
 [ 0.02823079  0.11901567 -0.09392691 ...  0.07328403  0.06178817
   0.11281601]
 [-0.28925682 -0.00127559  0.00252567 ...  0.1608646  -0.02792966
   0.04272088]]


In [19]:
x = np.arange(20)

print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [20]:
x = np.reshape(x, (4, 5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [21]:
x = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


### Accessing, Deleting and Inserting Elements into ndarrays

In [22]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [23]:
print('1st element:', x[0])
print('3rd element:', x[2])
print('Last element:', x[-1])

1st element: 1
3rd element: 3
Last element: 5


In [24]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [25]:
x = np.arange(1, 10).reshape(3, 3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
print('Element at 1st row, 2nd column:', x[0, 1])
print('Element at 3rd row, 1st column:', x[2, 0])

Element at 1st row, 2nd column: 2
Element at 3rd row, 1st column: 7


In [27]:
x[0,0] = 20
print(x)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [28]:
w = np.delete(x, 1, axis=1)  # Delete 2nd column
print(w)

[[20  3]
 [ 4  6]
 [ 7  9]]


In [29]:
y = np.append(w, [[10], [11], [12]], axis=1)  # Append new column
print(y)

[[20  3 10]
 [ 4  6 11]
 [ 7  9 12]]


In [30]:
x = np.array([1, 2, 5, 6, 7])

Y = np.array([[1, 2, 3], [7, 8, 9]])

print(x)
print()
print(Y)

[1 2 5 6 7]

[[1 2 3]
 [7 8 9]]


In [31]:
x = np.insert(x, 3, 3)  # Insert '3' at index 3
print(x)

[1 2 5 3 6 7]


In [32]:
w = np.insert(Y, 2, [4, 5, 6], axis=0)  # Insert new row at index 1
print(w)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [33]:
x = np.array([1, 2])

Y = np.array([[3, 4], [5, 6]])

print(x)
print()
print(Y)

[1 2]

[[3 4]
 [5 6]]


In [34]:
z = np.vstack((x, Y)) # Stack arrays vertically
print(z)

[[1 2]
 [3 4]
 [5 6]]


Slicing ndarrays
1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

nb: the end index in 1 and 3 are excluded

In [35]:
x = np.arange(1, 21).reshape(4, 5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [36]:
z = x[1:4, 2:5] # Slicing rows 1 to 3 and columns 2 to 4
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [37]:
z = x[:, 2]
print(z)

[ 3  8 13 18]


In [38]:
z = x[:, 2:3]
print(z)

[[ 3]
 [ 8]
 [13]
 [18]]


In [39]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [40]:
z = x[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [41]:
z[2, 2] = 100
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 100]]


In [42]:
print(x)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 100]]


In [43]:
x = np.arange(1, 21).reshape(4, 5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [44]:
z = x[1:, 2:].copy()
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [45]:
z[2, 2] = 100
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 100]]


In [46]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [47]:
indices = np.array([1, 3])
print(indices)

[1 3]


In [48]:
y = x[indices, :]
print(y)

[[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [49]:
z = x[:, indices]
print(z)

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


In [50]:
z = np.diag(x)
print(z)

[ 1  7 13 19]


### Boolean Indexing, Set Operations and Sorting

In [51]:
X = np.arange(25).reshape(5, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [52]:
print(X[X > 10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [53]:
print(X[X <= 7])

[0 1 2 3 4 5 6 7]


In [54]:
print(X[(X > 5) & (X < 15)])

[ 6  7  8  9 10 11 12 13 14]


In [55]:
X[(X > 5) & (X < 15)] = 0
print(X)

[[ 0  1  2  3  4]
 [ 5  0  0  0  0]
 [ 0  0  0  0  0]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [56]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.union1d(x, y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [57]:
x = np.random.randint(0, 100, 10)
print(x)

[96 43 89 65 71 95 36 58 49 51]


In [58]:
print(np.sort(x))
print(x)

[36 43 49 51 58 65 71 89 95 96]
[96 43 89 65 71 95 36 58 49 51]


In [59]:
print(x)

[96 43 89 65 71 95 36 58 49 51]


In [60]:
x.sort()
print(x)

[36 43 49 51 58 65 71 89 95 96]


In [61]:
x = np.random.randint(0, 100, size=(5, 5))
print(x)

[[51  4 30  9  1]
 [35  8 27 33 75]
 [32 87 10 99 55]
 [86 81 55 56 65]
 [ 1 33 25 38 88]]


In [62]:
print(np.sort(x, axis=0))  # Sort each column
print()
print(np.sort(x, axis=1))  # Sort each row

[[ 1  4 10  9  1]
 [32  8 25 33 55]
 [35 33 27 38 65]
 [51 81 30 56 75]
 [86 87 55 99 88]]

[[ 1  4  9 30 51]
 [ 8 27 33 35 75]
 [10 32 55 87 99]
 [55 56 65 81 86]
 [ 1 25 33 38 88]]


#### Arithemetics 

In [63]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

#### Arithemetics
print("x + y =", x + y)

x + y = [ 6  8 10 12]


In [64]:
print("y - x =", y - x)

y - x = [4 4 4 4]


In [65]:
print("x * y =", x * y)

x * y = [ 5 12 21 32]


In [66]:
X = np.array([[1, 2], [3, 4]])
print("X:\n", X)

X:
 [[1 2]
 [3 4]]


In [67]:
Y = np.array([[5, 6], [7, 8]])
print("Y:\n", Y)

Y:
 [[5 6]
 [7 8]]


In [69]:
print("x * y =", X * Y)
print()
print("X + Y =\n", X + Y)
print()
print("X - Y =\n", X - Y)  # Element-wise subtraction
print()
print("X / Y =\n", X / Y)  # Element-wise division

x * y = [[ 5 12]
 [21 32]]

X + Y =
 [[ 6  8]
 [10 12]]

X - Y =
 [[-4 -4]
 [-4 -4]]

X / Y =
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [70]:
Y = np.arange(9).reshape(3, 3)
print(Y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [71]:
x = np.arange(3)
print("x:\n", x)

x:
 [0 1 2]


In [72]:
print("x + Y =\n", x + Y)  # Broadcasting

x + Y =
 [[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [73]:
z = np.arange(3).reshape(3, 1)
print("z:\n", z)

z:
 [[0]
 [1]
 [2]]


In [74]:
print(Y + z)  # Broadcasting

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
