### Numpy
This section is for learning numpy

In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

In [2]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
x.dtype

dtype('int64')

In [4]:
x.shape

(5,)

In [5]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(Y)
print(Y.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [6]:
x = np.zeros((3, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
x = np.full((2, 3), 7)
print(x)

[[7 7 7]
 [7 7 7]]


In [8]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
x = np.diag([1, 2, 3, 4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [10]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
x = np.arange(4, 20, 3)
print(x)

[ 4  7 10 13 16 19]


In [12]:
x = np.linspace(0, 25, 10, endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [13]:
x = np.arange(20)
print(x.reshape(4, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
x = np.reshape(x, (10, 2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [15]:
x = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [16]:
x = np.random.random((2, 3))
print(x)

[[0.19636745 0.3069744  0.92620471]
 [0.83259121 0.74715984 0.29448003]]


In [17]:
x = np.random.randint(0, 10, (3, 4))
print(x)

[[3 1 1 1]
 [2 4 1 7]
 [8 6 4 5]]


In [18]:
x = np.random.normal(0, 0.1, (1000, 1000))
print(x)

[[-0.03029335  0.0771339  -0.08085442 ...  0.23356211 -0.02933746
  -0.06603719]
 [-0.15141426 -0.00344064 -0.12216975 ...  0.10103337 -0.10554552
   0.10136178]
 [-0.05434996 -0.16987894 -0.13623735 ... -0.05704988  0.02860386
   0.11355858]
 ...
 [ 0.03567391 -0.03424583 -0.07473871 ... -0.06268614  0.04612944
  -0.18875939]
 [ 0.07432117  0.22616257  0.05695183 ...  0.0011544  -0.10285068
  -0.17581824]
 [ 0.12611863  0.18570745  0.02397172 ...  0.18873934  0.01463251
  -0.00856062]]


In [19]:
x = np.arange(20)

print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [20]:
x = np.reshape(x, (4, 5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [21]:
x = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


### Accessing, Deleting and Inserting Elements into ndarrays

In [22]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [23]:
print('1st element:', x[0])
print('3rd element:', x[2])
print('Last element:', x[-1])

1st element: 1
3rd element: 3
Last element: 5


In [24]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [25]:
x = np.arange(1, 10).reshape(3, 3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
print('Element at 1st row, 2nd column:', x[0, 1])
print('Element at 3rd row, 1st column:', x[2, 0])

Element at 1st row, 2nd column: 2
Element at 3rd row, 1st column: 7


In [27]:
x[0,0] = 20
print(x)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [28]:
w = np.delete(x, 1, axis=1)  # Delete 2nd column
print(w)

[[20  3]
 [ 4  6]
 [ 7  9]]


In [29]:
y = np.append(w, [[10], [11], [12]], axis=1)  # Append new column
print(y)

[[20  3 10]
 [ 4  6 11]
 [ 7  9 12]]


In [30]:
x = np.array([1, 2, 5, 6, 7])

Y = np.array([[1, 2, 3], [7, 8, 9]])

print(x)
print()
print(Y)

[1 2 5 6 7]

[[1 2 3]
 [7 8 9]]


In [31]:
x = np.insert(x, 3, 3)  # Insert '3' at index 3
print(x)

[1 2 5 3 6 7]


In [33]:
w = np.insert(Y, 2, [4, 5, 6], axis=0)  # Insert new row at index 1
print(w)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [34]:
x = np.array([1, 2])

Y = np.array([[3, 4], [5, 6]])

print(x)
print()
print(Y)

[1 2]

[[3 4]
 [5 6]]


In [36]:
z = np.vstack((x, Y)) # Stack arrays vertically
print(z)

[[1 2]
 [3 4]
 [5 6]]
