### Numpy
This section is for learning numpy

In [2]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

In [3]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
x.dtype

dtype('int64')

In [5]:
x.shape

(5,)

In [6]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(Y)
print(Y.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [7]:
x = np.zeros((3, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
x = np.full((2, 3), 7)
print(x)

[[7 7 7]
 [7 7 7]]


In [9]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
x = np.diag([1, 2, 3, 4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [11]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
x = np.arange(4, 20, 3)
print(x)

[ 4  7 10 13 16 19]


In [13]:
x = np.linspace(0, 25, 10, endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [14]:
x = np.arange(20)
print(x.reshape(4, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [15]:
x = np.reshape(x, (10, 2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [16]:
x = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [17]:
x = np.random.random((2, 3))
print(x)

[[0.31636452 0.641529   0.62264815]
 [0.85398448 0.23349833 0.86268992]]


In [18]:
x = np.random.randint(0, 10, (3, 4))
print(x)

[[7 8 7 5]
 [7 2 9 0]
 [8 1 9 7]]


In [19]:
x = np.random.normal(0, 0.1, (1000, 1000))
print(x)

[[ 0.10020424  0.09287706 -0.06233892 ...  0.06350187  0.05577806
   0.02311701]
 [-0.03364196 -0.08160247  0.01270828 ... -0.0805363  -0.07910629
   0.02664442]
 [-0.01279708  0.02053318  0.13422056 ...  0.00410503 -0.22790514
  -0.1521902 ]
 ...
 [ 0.16752684 -0.1121003  -0.09260245 ...  0.21741188  0.1608622
   0.01096875]
 [-0.10197339 -0.05011971  0.01195119 ...  0.10796317 -0.0734073
   0.07781814]
 [ 0.21409027  0.10010274 -0.00690662 ... -0.06186347  0.06189388
   0.10851578]]


In [20]:
x = np.arange(20)

print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [21]:
x = np.reshape(x, (4, 5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [22]:
x = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


### Accessing, Deleting and Inserting Elements into ndarrays

In [23]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [24]:
print('1st element:', x[0])
print('3rd element:', x[2])
print('Last element:', x[-1])

1st element: 1
3rd element: 3
Last element: 5


In [25]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [26]:
x = np.arange(1, 10).reshape(3, 3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
print('Element at 1st row, 2nd column:', x[0, 1])
print('Element at 3rd row, 1st column:', x[2, 0])

Element at 1st row, 2nd column: 2
Element at 3rd row, 1st column: 7


In [28]:
x[0,0] = 20
print(x)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [29]:
w = np.delete(x, 1, axis=1)  # Delete 2nd column
print(w)

[[20  3]
 [ 4  6]
 [ 7  9]]


In [30]:
y = np.append(w, [[10], [11], [12]], axis=1)  # Append new column
print(y)

[[20  3 10]
 [ 4  6 11]
 [ 7  9 12]]


In [31]:
x = np.array([1, 2, 5, 6, 7])

Y = np.array([[1, 2, 3], [7, 8, 9]])

print(x)
print()
print(Y)

[1 2 5 6 7]

[[1 2 3]
 [7 8 9]]


In [32]:
x = np.insert(x, 3, 3)  # Insert '3' at index 3
print(x)

[1 2 5 3 6 7]


In [33]:
w = np.insert(Y, 2, [4, 5, 6], axis=0)  # Insert new row at index 1
print(w)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [34]:
x = np.array([1, 2])

Y = np.array([[3, 4], [5, 6]])

print(x)
print()
print(Y)

[1 2]

[[3 4]
 [5 6]]


In [35]:
z = np.vstack((x, Y)) # Stack arrays vertically
print(z)

[[1 2]
 [3 4]
 [5 6]]


Slicing ndarrays
1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

nb: the end index in 1 and 3 are excluded

In [36]:
x = np.arange(1, 21).reshape(4, 5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [37]:
z = x[1:4, 2:5] # Slicing rows 1 to 3 and columns 2 to 4
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [38]:
z = x[:, 2]
print(z)

[ 3  8 13 18]


In [39]:
z = x[:, 2:3]
print(z)

[[ 3]
 [ 8]
 [13]
 [18]]


In [40]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [41]:
z = x[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [42]:
z[2, 2] = 100
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 100]]


In [43]:
print(x)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 100]]


In [44]:
x = np.arange(1, 21).reshape(4, 5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [45]:
z = x[1:, 2:].copy()
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [46]:
z[2, 2] = 100
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 100]]


In [47]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [48]:
indices = np.array([1, 3])
print(indices)

[1 3]


In [49]:
y = x[indices, :]
print(y)

[[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [50]:
z = x[:, indices]
print(z)

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


In [51]:
z = np.diag(x)
print(z)

[ 1  7 13 19]


### Boolean Indexing, Set Operations and Sorting

In [52]:
X = np.arange(25).reshape(5, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [53]:
print(X[X > 10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [54]:
print(X[X <= 7])

[0 1 2 3 4 5 6 7]


In [55]:
print(X[(X > 5) & (X < 15)])

[ 6  7  8  9 10 11 12 13 14]


In [56]:
X[(X > 5) & (X < 15)] = 0
print(X)

[[ 0  1  2  3  4]
 [ 5  0  0  0  0]
 [ 0  0  0  0  0]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [57]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.union1d(x, y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [58]:
x = np.random.randint(0, 100, 10)
print(x)

[91 75 26  7 63 60 76  6 30 66]


In [59]:
print(np.sort(x))
print(x)

[ 6  7 26 30 60 63 66 75 76 91]
[91 75 26  7 63 60 76  6 30 66]


In [60]:
print(x)

[91 75 26  7 63 60 76  6 30 66]


In [61]:
x.sort()
print(x)

[ 6  7 26 30 60 63 66 75 76 91]


In [62]:
x = np.random.randint(0, 100, size=(5, 5))
print(x)

[[73 61 54 66  3]
 [81 13 58 33 80]
 [10  4 11 62 23]
 [40 23 58 16 18]
 [96  7 89 36 42]]


In [63]:
print(np.sort(x, axis=0))  # Sort each column
print()
print(np.sort(x, axis=1))  # Sort each row

[[10  4 11 16  3]
 [40  7 54 33 18]
 [73 13 58 36 23]
 [81 23 58 62 42]
 [96 61 89 66 80]]

[[ 3 54 61 66 73]
 [13 33 58 80 81]
 [ 4 10 11 23 62]
 [16 18 23 40 58]
 [ 7 36 42 89 96]]


#### Arithemetics 

In [64]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

#### Arithemetics
print("x + y =", x + y)

x + y = [ 6  8 10 12]


In [65]:
print("y - x =", y - x)

y - x = [4 4 4 4]


In [66]:
print("x * y =", x * y)

x * y = [ 5 12 21 32]


In [67]:
X = np.array([[1, 2], [3, 4]])
print("X:\n", X)

X:
 [[1 2]
 [3 4]]


In [68]:
Y = np.array([[5, 6], [7, 8]])
print("Y:\n", Y)

Y:
 [[5 6]
 [7 8]]


In [69]:
print("x * y =", X * Y)
print()
print("X + Y =\n", X + Y)
print()
print("X - Y =\n", X - Y)  # Element-wise subtraction
print()
print("X / Y =\n", X / Y)  # Element-wise division

x * y = [[ 5 12]
 [21 32]]

X + Y =
 [[ 6  8]
 [10 12]]

X - Y =
 [[-4 -4]
 [-4 -4]]

X / Y =
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [70]:
Y = np.arange(9).reshape(3, 3)
print(Y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [71]:
x = np.arange(3)
print("x:\n", x)

x:
 [0 1 2]


In [72]:
print("x + Y =\n", x + Y)  # Broadcasting

x + Y =
 [[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [73]:
z = np.arange(3).reshape(3, 1)
print("z:\n", z)

z:
 [[0]
 [1]
 [2]]


In [74]:
print(Y + z)  # Broadcasting

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [75]:
import pandas as pd

nyc_store_items = [
    {'location': 'Manhattan', 'shirts': 25, 'pants': 40, 'shoes': 30, 'hats': np.nan},
    {'location': 'Brooklyn', 'shirts': 18, 'pants': np.nan, 'shoes': 22, 'hats': 12},
    {'location': 'Queens', 'shirts': np.nan, 'pants': 35, 'shoes': 28, 'hats': 10},
    {'location': 'Bronx', 'shirts': 20, 'pants': 30, 'shoes': np.nan, 'hats': 8},
    {'location': 'Staten Island', 'shirts': 15, 'pants': 25, 'shoes': 20, 'hats': np.nan}
]
nyc_store_items_df = pd.DataFrame(nyc_store_items)
nyc_store_items_df = nyc_store_items_df.set_index('location')
nyc_store_items_df

shirts  pants  shoes  hats
location                                 
Manhattan        25.0   40.0   30.0   NaN
Brooklyn         18.0    NaN   22.0  12.0
Queens            NaN   35.0   28.0  10.0
Bronx            20.0   30.0    NaN   8.0
Staten Island    15.0   25.0   20.0   NaN