### Numpy
This section is for learning numpy

In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

In [2]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
x.dtype

dtype('int64')

In [4]:
x.shape

(5,)

In [5]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(Y)
print(Y.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [6]:
x = np.zeros((3, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
x = np.full((2, 3), 7)
print(x)

[[7 7 7]
 [7 7 7]]


In [9]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
x = np.diag([1, 2, 3, 4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [11]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
x = np.arange(4, 20, 3)
print(x)

[ 4  7 10 13 16 19]


In [17]:
x = np.linspace(0, 25, 10, endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [18]:
x = np.arange(20)
print(x.reshape(4, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [22]:
x = np.reshape(x, (10, 2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [23]:
x = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [24]:
x = np.random.random((2, 3))
print(x)

[[0.9254827  0.25681026 0.90631028]
 [0.27172349 0.17243647 0.1873452 ]]


In [25]:
x = np.random.randint(0, 10, (3, 4))
print(x)

[[5 8 8 2]
 [6 2 4 4]
 [9 9 0 3]]


In [26]:
x = np.random.normal(0, 0.1, (1000, 1000))
print(x)

[[ 0.28219404  0.06036205  0.09541098 ...  0.10429621  0.05386891
  -0.17743785]
 [ 0.07536758 -0.12586423 -0.10407183 ...  0.01266954 -0.04629343
   0.09559747]
 [-0.16263052  0.05573749  0.01953381 ...  0.19110369  0.00579987
   0.10886755]
 ...
 [ 0.02894538  0.09620246  0.17165148 ... -0.06478569  0.00808399
  -0.04881892]
 [ 0.17375322  0.02971306 -0.28246728 ... -0.07006204 -0.15843572
  -0.05999381]
 [-0.05752076 -0.09352959 -0.13269698 ...  0.10302003  0.07168018
  -0.00415486]]
